---
Refsheets:
  spellSheetID: 1cuwb3QSvWDD7GG5McdvyyRBpqycYuKMRsXgyrvxvLFI
  featsSheetID: 1XqQO21AyE2WtLwW0wSjA9ov74A9tmJmVJjrhPK54JHQ
  magicItemsSheetID: 1NQhHjDXhvFZkMiu09epBXsVwCI6YENg-AUQhF-v5ntU
  bestiarySheetID: 1StTeUz_ZBU3pNlW120msjUX34p9cs7kqQbZ2Ym7cSBE
