// Code generated by "stringer -type=Race,Ability -output enum_string.go"; DO NOT EDIT.

package pathfinder

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Dwarf-0]
	_ = x[Elf-1]
	_ = x[Gnome-2]
	_ = x[HalfElf-3]
	_ = x[HalfOrc-4]
	_ = x[Halfling-5]
	_ = x[Human-6]
}

const _Race_name = "DwarfElfGnomeHalfElfHalfOrcHalflingHuman"

var _Race_index = [...]uint8{0, 5, 8, 13, 20, 27, 35, 40}

func (i Race) String() string {
	if i < 0 || i >= Race(len(_Race_index)-1) {
		return "Race(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Race_name[_Race_index[i]:_Race_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Strength-0]
	_ = x[Dexterity-1]
	_ = x[Constitution-2]
	_ = x[Intelligence-3]
	_ = x[Wisdom-4]
	_ = x[Charisma-5]
}

const _Ability_name = "StrengthDexterityConstitutionIntelligenceWisdomCharisma"

var _Ability_index = [...]uint8{0, 8, 17, 29, 41, 47, 55}

func (i Ability) String() string {
	if i < 0 || i >= Ability(len(_Ability_index)-1) {
		return "Ability(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Ability_name[_Ability_index[i]:_Ability_index[i+1]]
}
